name: "📌 Pull Request"
description: "새로운 기능, 버그 수정, 리팩토링 등의 변경 사항을 제출합니다."
body:
  - type: textarea
    attributes:
      label: 🎯 PR 개요
      description: 이번 PR에서 변경된 주요 내용을 간략히 설명해주세요.
      placeholder: 새로운 기능 추가, 버그 수정, 리팩토링 등의 내용을 요약해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📑 변경 사항
      description: 변경된 내용을 자세히 설명해주세요.
      placeholder: 코드 변경, API 수정, UI 개선 등의 내용을 포함해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🛠 테스트 내용
      description: 변경 사항을 어떻게 테스트했는지 설명해주세요.
      placeholder: 유닛 테스트, 통합 테스트 등
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📝 참고 사항
      description: 관련된 이슈, 문서 또는 추가 설명이 필요하면 작성해주세요.
  - type: checkboxes
    attributes:
      label: ✅ 체크리스트
      description: PR을 제출하기 전에 아래 항목들을 확인해주세요.
      options:
        - label: [ ] 코드가 정상적으로 동작하며, 기존 기능을 해치지 않습니다.
        - label: [ ] 코드 스타일 가이드에 맞춰 포맷팅되었습니다.
        - label: [ ] 필요한 경우 관련 문서를 업데이트했습니다.
        - label: [ ] 테스트를 실행하고 모든 테스트가 통과했습니다.
